In [34]:
import numpy as np

# array 생성하는 법
arr = np.array([1,2,3,4,5])
print(arr) # [1 2 3 4 5]

# array의 모양(행,열)
print(arr.shape) # (5,)

# array의 차원
print(arr.ndim) # 1


arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)
"""
[[1 2 3]
 [4 5 6]]
"""

print(arr2.shape) # (2, 3)
print(arr2.ndim) # 2


[1 2 3 4 5]
(5,)
1
[[1 2 3]
 [4 5 6]]
(2, 3)
2


'\n[[1 2 3]\n [4 5 6]]\n'

In [8]:
import numpy as np

# zeros : parameter에 행과 열 수 만큼 0값들을 가진 행렬을 만든다

arr_0 = np.zeros((3,6)) # (row,column)
print(arr_0)
print(type(arr_0)) # <class 'numpy.ndarray'>

"""
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
"""

# parameter에 행과 열 수 만큼 1값들을 가진 행렬을 만든다

arr_1 = np.ones((2,4)) # (row,column)
print(arr_1)

"""
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
"""

# eye : 단위행렬을 만드는 함수이다. parameter값은 행렬 사이즈이다
arr_eye = np.eye(5)
print(arr_eye)
print(type(arr_eye))# <class 'numpy.ndarray'>

"""
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
"""

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
<class 'numpy.ndarray'>
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
<class 'numpy.ndarray'>


'\n[[1. 0. 0. 0. 0.]\n [0. 1. 0. 0. 0.]\n [0. 0. 1. 0. 0.]\n [0. 0. 0. 1. 0.]\n [0. 0. 0. 0. 1.]]\n'

In [14]:
import numpy as np

# arange : parameter의 범위만큼의 1차원 array를 만드는 함수, 끝값은 포함을 하지 않는다
arr = np.arange(1,10)
print(arr) # [1 2 3 4 5 6 7 8 9]

# reshape : array의 형태를 바꿔주는 함수 (row,column) 형태로 바뀜

new_arr = arr.reshape(3,3)
print(new_arr)
"""
[[1 2 3]
 [4 5 6]
 [7 8 9]]
"""

# reshape를 한 뒤, 새로운 변수에 저장해야합니다.

arr.reshape(9,1)
print(arr) # [1 2 3 4 5 6 7 8 9]

# 한줄로도 표현이 가능합니다. 이 형태를 더 많이 사용합니다.
arr2 = np.arange(1,17).reshape(4,4)
print(arr2)
"""
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
"""

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [22]:
# 0 <= 실수 < 1로 행렬 채우기 : np.random.random(배열의 크기)
arr = np.random.random((2,4))
print(arr)
"""
[[0.54803379 0.77835502 0.70255043 0.16068691]
 [0.65812631 0.79997614 0.09721328 0.45088333]]
"""

# a <= 실수 < b로 행렬 채우기 : np.random.uniform(a,b, 배열의 크기)
arr1 = np.random.uniform(3, 5.5,(3,3))
print(arr1)
"""
[[4.42427523 4.23330886 4.85055266]
 [5.19868744 3.04569855 5.3735318 ]
 [4.23635241 3.82002581 5.28032314]]
"""

# a <= 정수 < b로 행렬 채우기 : np.random.randint(a,b, 배열의 크기)
arr2 = np.random.randint(1,10,(4,2))
print(arr2)
"""
[[2 2]
 [9 4]
 [6 2]
 [7 1]]
"""

[[0.89681002 0.97670612 0.27071329 0.0387956 ]
 [0.08197438 0.14312617 0.64063006 0.7845682 ]]
[[4.06847648 5.38881896 5.21933161]
 [5.06571547 4.06553346 5.41902749]
 [3.04700793 4.10051634 4.8183994 ]]
[[1 3]
 [8 8]
 [4 3]
 [8 5]]
[[-5  3  0]
 [ 0 -4 -5]
 [ 1  1 -3]
 [ 4  0  1]
 [ 1 -4 -5]
 [-5  0  4]
 [-2 -1 -4]]


In [38]:
import numpy as np

# linspace : 동일 간격으로 등분한 array를 생성하는 함수
# np.linspace(시작,끝,숫자개수) *끝도 포함합니다.
a = np.linspace(0,15,4)
print(a) # [ 0.  5. 10. 15.]

b = np.linspace(0,25,6).reshape(2,3)
print(b)
"""
[[ 0.  5. 10.]
 [15. 20. 25.]]
"""

# Transpose : 행과 열을 교체하는 함수, 전치

arr = np.arange(1,11).reshape(2,5)
print(arr)

"""
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
"""

arr = arr.T
print(arr)

"""
[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]

"""

# 한줄로 작성 가능

arr2 = np.arange(1,11).reshape(2,5).T
print(arr2)

"""
[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]
"""


[ 0.  5. 10. 15.]
[[ 0.  5. 10.]
 [15. 20. 25.]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]
[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


In [43]:
# array slicing

import numpy as np

arr = np.arange(1,13).reshape(3,4)
print(arr)

"""
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
"""

# arr[0:2] : 0~1 인덱스까지 row slicing
print(arr[0:2])
"""
[[1 2 3 4]
 [5 6 7 8]]
"""

# 슬라이싱을 해도, 따로 변수에 저장하지 않는 이상, 원본은 변하지 않음
print(arr)
"""
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
"""

# arr[0:2, 0:3] 행 : 0~1, 열 : 0~2까지 슬라이싱
print(arr[0:2,0:3])

"""
[[1 2 3]
 [5 6 7]]
"""

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1 2 3 4]
 [5 6 7 8]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1 2 3]
 [5 6 7]]


In [45]:
# Numpy array 연산
# 배열화 계산이라고 하며, 원소 하나 하나씩 계산하는 것이 아니라
# 배열 단위로 계산을 합니다.
# 병렬처리가 가능합니다. (multi-core)

# list 연산 vs array연산
import numpy as np

a = [1,2,3,4]
b = a*3
print(b) # [1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

a = np.arange(1,5)*3
print(a) # [ 3  6  9 12]



[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]
[ 3  6  9 12]


In [62]:
# Numpy는 사칙연산, 논리연산, 비교 연산, 지수,로그함수등
# 다양한 연산이 가능합니다.
# 지수 Exp, **, 
# 로그 log()
import numpy as np

a = np.arange(1,6)
b = np.ones((5,))*10
print(a) # [1 2 3 4 5]
print(b) # [10. 10. 10. 10. 10.]

# 논리 연산
print(a>2) # [False False  True  True  True]

# 지수 연산
print((a+b)**2) # [121. 144. 169. 196. 225.]

# exp : 자연 상수 e를 밑으로 지수 연산 수행

print(np.exp(a)) # [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


[1 2 3 4 5]
[10. 10. 10. 10. 10.]
[False False  True  True  True]
[121. 144. 169. 196. 225.]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [65]:
# 브로드캐스팅(broadcasting)
# Broadcasting이란 사전적인 의미론 퍼뜨리다라는 뜻으로, 
# A라는 행렬과 B라는 연산시, B라는 행렬의 크기가 작다면, B의 행렬의 크기를 늘려주는 것을 의미합니다.

arr = np.arange(1,13).reshape(4,3)
print(arr)

"""
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
"""

arr2 = np.arange(3,)
print(arr2) # [0 1 2]

res = arr+arr2
print(res)

"""
[[ 1  3  5]
 [ 4  6  8]
 [ 7  9 11]
 [10 12 14]]
"""

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[0 1 2]
[[ 1  3  5]
 [ 4  6  8]
 [ 7  9 11]
 [10 12 14]]


In [77]:
# Min, Max, Argmin, Argmax

import numpy as np

arr = np.random.randint(1,10,(4,3))
print(arr)

"""
[[2 5 6]
 [9 9 2]
 [7 2 1]
 [9 8 1]]
"""

# max : arr에서 가장 큰 값을 출력
print(np.max(arr)) # 9
print(arr.max()) # 9

# min : arr에서 가장 작은 값을 출력
print(np.min(arr)) # 1
print(arr.min()) # 1

# argmin : 최소의 위치를 반환
print(np.argmin(arr)) # 8 (인덱스 기준이므로 8번째)
print(arr.argmin()) # 8 (인덱스 기준이므로 8번째)

# argmax : 최대의 위치를 반환
print(np.argmax(arr)) # 3 (인덱스 기준이므로 3번째)
print(arr.argmax()) # 3 (인덱스 기준이므로 3번째)


[[2 5 6]
 [9 9 2]
 [7 2 1]
 [9 8 1]]
9
9
1
1
8
8
3
3


In [80]:
# sum , mean, median

import numpy as np

arr = np.arange(1,31,2).reshape(3,5)
print(arr)
"""
[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]]
"""

# sum : array의 합을 출력해주는 함수
print(np.sum(arr)) # 225
print(arr.sum()) # 225

# mean : array의 평균을 출력해주는 함수
print(np.mean(arr)) # 15.0
print(arr.mean()) # 15.0

# median : array의 중간값을 출력해주는 함수
print(np.median(arr)) # 15.0
#print(arr.median()) # 동작하지 않음

[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]]
225
225
15.0
15.0
15.0


In [93]:
import numpy as np 

# axix를 이용한 sum, mean, median
arr2 = np.arange(1,31,2).reshape(3,5)
print(arr2)
"""
[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]]
"""

# arr2 전체 item들의 합
print(arr2.sum()) # 225

# arr2를 행 기준으로 합
print(arr2.sum(axis = 0)) # [33 39 45 51 57]

# arr2를 열 기준으로 합
print(arr2.sum(axis = 1)) # [ 25  75 125]

# arr2를 행 기준으로 평균을 구함
print(arr2.mean(axis = 0)) # [11. 13. 15. 17. 19.]

# arr2를 열 기준으로 평균을 구함
print(arr2.mean(axis = 1)) # [ 5. 15. 25.]


# 1,4 번째 열을 제외한 부분의 행렬의 최대,최소,평균,중간 값을 구하시오
print(np.max(arr[:,1:4])) # 27
print(np.min(arr[:,1:4])) # 3
print(np.mean(arr[:,1:4])) # 15.0
print(np.median(arr[:,1:4])) # 15.0

[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]]
225
[33 39 45 51 57]
[ 25  75 125]
[11. 13. 15. 17. 19.]
[ 5. 15. 25.]
27
3
15.0
15.0


In [103]:
# 행렬곱 

import numpy as np

# 행렬끼리 곱을 하려면 @ 혹은 dot함수를 사용하면 된다

arr_1 = np.ones((3,3))
print(arr_1)

arr = np.ones((3,2))*3
print(arr)

print(arr_1@arr)
"""
[[9. 9.]
 [9. 9.]
 [9. 9.]]
"""

print(np.dot(arr_1,arr))

"""
[[9. 9.]
 [9. 9.]
 [9. 9.]]
"""


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[3. 3.]
 [3. 3.]
 [3. 3.]]
[[9. 9.]
 [9. 9.]
 [9. 9.]]
[[9. 9.]
 [9. 9.]
 [9. 9.]]


In [108]:
# numpy sort

import numpy as np

arr = np.arange(1,16)
np.random.shuffle(arr)
arr = arr.reshape(3,5)
print(arr)

"""
[[ 8 12  2  1  4]
 [ 9 14 15 13  6]
 [ 7  3 11  5 10]]
"""

# array의 item들을 순서대로 sort해줌
arr_sort = np.sort(arr)
print(arr_sort)
"""
[[ 1  2  4  8 12]
 [ 6  9 13 14 15]
 [ 3  5  7 10 11]]
"""

# axis = 0 행기준으로 sort
arr_sort2 = np.sort(arr, axis = 0)
print(arr_sort2)

"""
[[ 7  3  2  1  4]
 [ 8 12 11  5  6]
 [ 9 14 15 13 10]]
"""

# axis = 1 열기준으로 sort
arr_sort2 = np.sort(arr, axis = 1)
print(arr_sort2)

"""
[[ 1  2  4  8 12]
 [ 6  9 13 14 15]
 [ 3  5  7 10 11]]
"""

[[ 8 12  2  1  4]
 [ 9 14 15 13  6]
 [ 7  3 11  5 10]]
[[ 1  2  4  8 12]
 [ 6  9 13 14 15]
 [ 3  5  7 10 11]]
[[ 7  3  2  1  4]
 [ 8 12 11  5  6]
 [ 9 14 15 13 10]]
[[ 1  2  4  8 12]
 [ 6  9 13 14 15]
 [ 3  5  7 10 11]]


In [109]:
import numpy as np

# np.unique(array) : array의 값들을 정렬(중복 제거)하여 1차원으로 반환하는 함수

arr = np.random.randint(-10,10,(2,5))
print(arr)
"""
[[ -3   9   8   1 -10]
 [  3   7   3  -1   1]]
"""

print(np.unique(arr)) # [-10  -3  -1   1   3   7   8   9]

[[ -3   9   8   1 -10]
 [  3   7   3  -1   1]]
[-10  -3  -1   1   3   7   8   9]
